<?php
// Automatically Generated by TestLink Installer - Sat, 08 Apr 23 11:23:26 +0200
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'root.admin');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlinkPHP82');
define('DB_TABLE_PREFIX', '');
