--  -----------------------------------------------------------------------------------
-- TestLink Open Source Project - http://testlink.sourceforge.net/
-- This script is distributed under the GNU General Public License 2 or later.
-- $Id: testlink_create_tables.sql,v 1.1 2006/05/24 07:10:21 franciscom Exp $
--
-- SQL script - create db tables for TL
-- Database Type: Microsoft SQL Server
-- 
--  -----------------------------------------------------------------------------------
