/* 
	the format of the tree definition file is simple,
	you can find specification in the Tigra Menu documentation at:
	
	http://www.softcomplex.com/products/tigra_menu/docs/items.html	
*/

var TREE_ITEMS = [
	['Home', 'http://www.softcomplex.com/',
		['Products', 'http://www.softcomplex.com/products.html',
			['Server Side Components', 'http://www.softcomplex.com/products.html#server_side',
				['Advanced Web Security', null],
				['SC Object Environment', null],
			],
			['Client Side Components', 'http://www.softcomplex.com/products.html#client_side',
				['Tigra Menu', 'http://www.softcomplex.com/products/tigra_menu/',
					['Home Page', 'http://www.softcomplex.com/products/tigra_menu/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_menu/docs/'],
					['Online Builder', 'http://www.softcomplex.com/products/tigra_menu/builder/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=29'],
				],
				['Tigra Menu PRO', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_menu_pro/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_menu_pro/documentation/',
						['Documentation', 'http://www.softcomplex.com/products/tigra_menu_pro/documentation/'],
						['Frequently Asked Questions', 'http://www.softcomplex.com/products/tigra_menu_pro/documentation/faq.html'],
						['Terms and Conditions', 'http://www.softcomplex.com/products/tigra_menu_pro/documentation/terms_cond.html'],
					],
					['Online Builder', 'http://www.softcomplex.com/products/tigra_menu/builder/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=29'],
					['Order Form', 'https://secure.element5.com/shareit/checkout.html?productid=153541'],
					['Support Request', 'mailto:support@softcomplex.com?subject=Tigra Menu PRO support request. Order ID=[specify]'],
				],
				['Tigra Menu GOLD', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_menu_pro/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_menu_gold/docs/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=51'],
					['Order Form', 'https://secure.element5.com/shareit/checkout.html?productid=169414'],
					['Support Request', 'mailto:support@softcomplex.com?subject=Tigra Menu GOLD support request. Order ID=[specify]'],
				],
				['Tigra Tree Menu', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_tree_menu/content.html'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=31'],
				],
				['Tigra Calendar', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_calendar/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=30'],
				],
				['Tigra Calendar PRO', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_calendar_pro/'],
					['Order Form', 'https://secure.element5.com/shareit/checkout.html?productid=159443'],
					['Support Request', 'mailto:support@softcomplex.com?subject=Tigra Calendar PRO support request. Order ID=[specify]'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=30'],
				],
				['Tigra Scroller', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_scroller/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_scroller/docs/'],
					['Demo #1', 'http://www.softcomplex.com/products/tigra_scroller/demo1.html'],
					['Demo #2', 'http://www.softcomplex.com/products/tigra_scroller/demo2.html'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=49'],
				],
				['Tigra Scroller PRO', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_scroller_pro/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_scroller_pro/docs/'],
					['Demo #1', 'http://www.softcomplex.com/products/tigra_scroller_pro/demo1.html'],
					['Demo #2', 'http://www.softcomplex.com/products/tigra_scroller_pro/demo2.html'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=50'],
					['Order Form', 'https://secure.element5.com/shareit/checkout.html?productid=167102'],
					['Support Request', 'mailto:support@softcomplex.com?subject=Tigra Scroller PRO support request. Order ID=[specify]'],
				],
				['Tigra Tables', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_tables/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=32'],
				],
				['Tigra Tables PRO', null,
					['Home Page', 'http://www.softcomplex.com/products/tigra_tables_pro/'],
					['Documentation', 'http://www.softcomplex.com/products/tigra_tables_pro/docs/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=32'],
					['Order Form', 'https://secure.element5.com/shareit/checkout.html?productid=163419'],
					['Support Request', 'mailto:support@softcomplex.com?subject=Tigra Tables PRO support request. Order ID=[specify]'],
				],
			],
			['Online Services', 'http://www.softcomplex.com/products.html#online_services',
				['Tigra Menu Online Builder', null,
					['Login Page', 'http://www.softcomplex.com/products/tigra_menu/builder/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=33'],
					['Help Pages', null,
						['Horizontal Menu', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_horizontal_menu'],
						['Vertical Menu', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_vertical_menu'],
						['Item Path', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_path'],
						['Caption', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_caption'],
						['Link', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_link'],
						['Item Size', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_size'],
						['Block Offset', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_boffset'],
						['Saving Files', 'http://www.softcomplex.com/cgi-bin/builder/mgr.pl?class=static_page&action=view&tpl=help_save'],
					],
				],
			],
			['.NET Components', 'http://www.softcomplex.com/products.html#dotnet_components',
				['CoolLayout.Net', null,
					['Home Page', 'http://www.softcomplex.com/products/coollayout.net/'],
					['Documentation', 'http://www.softcomplex.com/products/coollayout.net/docs/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=34'],
				],
			],
			['ActiveX Components', 'http://www.softcomplex.com/products.html#activex_components',
				['ASP Upload Component', null,
					['Home Page', 'http://www.softcomplex.com/products/asp_upload_component/'],
					['Documentation', 'http://www.softcomplex.com/products/asp_upload_component/docs/'],
					['Forum', 'http://www.softcomplex.com/forum/forumdisplay.php?fid=35'],
				],
			]
		],
		['Services', 'http://www.softcomplex.com/services.html'],
		['Contacts', 'http://www.softcomplex.com/contacts.html'],
	]
];

