<?php
/**
 * TestLink Open Source Project - http://testlink.sourceforge.net/ 
 * This script is distributed under the GNU General Public License 2 or later. 
 *
 * Installation script - html footer
 * 
 * @package 	TestLink
 * @author 		Martin Havlat
 * @copyright 	2009, TestLink community 
 * @version    	CVS: $Id: installFooter.inc,v 1.1 2009/11/10 16:10:20 havlat Exp $
 *
 * @internal Revisions:
 * 	None.
 */
?>
    <section class="col-lg-6 col-md-8 col-sm-10 col-xs-12 col-lg-offset-3 col-md-offset-2 col-sm-offset-1 tl-box-footer"></section>
  </section> <!-- installHead.inc -->
</body>
</html>
