<?php
/**
 * TestLink Open Source Project - http://testlink.sourceforge.net/ 
 * This script is distributed under the GNU General Public License 2 or later. 
 *
 * Installation script - html footer
 * 
 * @package 	TestLink
 * @author 		Martin Havlat
 * @copyright 	2009, TestLink community 
 * @version    	CVS: $Id: installFooter.inc,v 1.1 2009/11/10 16:10:20 havlat Exp $
 *
 * @internal Revisions:
 * 	None.
 */
?>
<div class="tlLiner">&nbsp;</div>

</div>
</body>
</html>