<?php
/** 
*	TestLink Open Source Project - http://testlink.sourceforge.net/ 
* 	@version $Id: testSetNavigator.php,v 1.15 2006/08/17 19:29:59 schlundus Exp $
*	@author Martin Havlat 
*
* This page navigate according to Test Set. It builds the javascript trees 
* that allow the user to connect feature for choosen test suite or test case
* Used for 'treemenu' frame generated by frmWorkArea.php script.
*
*/ 	
require('../../config.inc.php');
require_once("common.php");
require_once("treeMenu.inc.php");
testlinkInitPage($db);

$workPath = null;

$tplan_mgr = new testplan($db);
$tplan_id = $_SESSION['testPlanId'];
$tproject_id = isset($_SESSION['testprojectID']) ? $_SESSION['testprojectID'] : 0;
$tproject_name = isset($_SESSION['testprojectName']) ? $_SESSION['testprojectName'] : '';

$keyword_id = 0;
$keywords_map = $tplan_mgr->get_keywords_map($tplan_id, " order by keyword "); 

if(!is_null($keywords_map))
{
	$keywords_map = array( 0 => '') + $keywords_map;
}
if(isset($_POST['filter']))
{
	$keyword_id = isset($_POST['keyword_id']) ? $_POST['keyword_id'] : 0;
}


// set feature data
if ($_GET['feature'] == 'removeTC')
{
	$menuUrl = "lib/plan/testSetRemove.php";
	$title = lang_get('title_test_plan_navigator');
	$tcHide = 0;
	$help_file = "testSetRemove.html";
}
elseif ($_GET['feature'] == 'priorityAssign')
{
	$menuUrl = "lib/plan/planOwner.php";
	$title = lang_get('title_test_plan_navigator');
	$tcHide = 1;
	$help_file = "planOwnerAndPriority.html";
}
else
{
	tLog("Wrong or missing GET argument 'feature'.", 'ERROR');
	exit();
}

define('FILTER_BY_BUILD_OFF',0);
define('FILTER_BY_TC_OFF',null);
define('FILTER_BY_OWNER_OFF',0);
define('FILTER_BY_TC_STATUS_OFF',null);

$sMenu = generateExecTree($db,$menuUrl,$tproject_id,$tproject_name,$tplan_id,$_SESSION['testPlanName'],
                          FILTER_BY_BUILD_OFF,null,
                          $keyword_id,FILTER_BY_TC_OFF);

$tree = invokeMenu($sMenu);


$smarty = new TLSmarty();
$smarty->assign('treeKind', TL_TREE_KIND);
$smarty->assign('tree', $tree);
$smarty->assign('keywords_map', $keywords_map);
$smarty->assign('keyword_id', $keyword_id);

$smarty->assign('treeHeader', $title);
$smarty->assign('menuUrl',$menuUrl);
$smarty->assign('SP_html_help_file',TL_INSTRUCTIONS_RPATH . $_SESSION['locale'] ."/". $help_file);
$smarty->display('testSetNavigator.tpl');
?>
